---
version: "2"

run:
  timeout: 5m

output:
  sort-results: true

linters:
  enable:
    - depguard
    - gosec
    - misspell
    - revive
  settings:
    gosec:
      severity: medium
      confidence: medium

formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/prometheus/prometheus
    gofumpt:
      extra-rules: true
