{
 "title": "Snowflake data ownership",
 "tags": [ "snowflake-mixin" ],
 "time": { "from": "now-8h", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(snowflake_successful_login_rate{job=\"integrations/snowflake\"}, job)"
   },
   {
    "name": "instance",
    "label": "Exporter instance",
    "query": "label_values(snowflake_successful_login_rate{job=\"integrations/snowflake\",job=~\"$job\"}, instance)"
   },
   {
    "name": "database_name",
    "label": "Database",
    "query": "label_values(snowflake_table_active_bytes{job=\"integrations/snowflake\",job=~\"$job\",instance=~\"$instance\"}, database_name)"
   },
   {
    "name": "schema_name",
    "label": "Schema",
    "query": "label_values(snowflake_table_active_bytes{job=\"integrations/snowflake\",job=~\"$job\",instance=~\"$instance\", database_name=~\"$database_name\"}, schema_name)"
   },
   {
    "name": "table_name",
    "query": "label_values(snowflake_table_active_bytes{job=\"integrations/snowflake\",job=~\"$job\",instance=~\"$instance\", database_name=~\"$database_name\", schema_name=~\"$schema_name\"}, table_name)"
   }
  ]
 },
 "panels": [
  { "title": "Data ownership", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Active schema owned data",
   "type": "timeseries",
   "description": "Amount of active data owned by the selected schema.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance,database_name,schema_name) (last_over_time(snowflake_table_active_bytes{job=\"integrations/snowflake\",job=~\"$job\",instance=~\"$instance\", database_name=~\"$database_name\", schema_name=~\"$schema_name\"}[24h]))",
     "legendFormat": "{{instance}} - {{database_name}} - {{schema_name}}"
    }
   ]
  },
  {
   "title": "Fail-safe schema owned data",
   "type": "timeseries",
   "description": "Amount of fail-safe data owned by the selected schema.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance,database_name,schema_name) (last_over_time(snowflake_table_failsafe_bytes{job=\"integrations/snowflake\",job=~\"$job\",instance=~\"$instance\", database_name=~\"$database_name\", schema_name=~\"$schema_name\"}[24h]))",
     "legendFormat": "{{instance}} - {{database_name}} - {{schema_name}}"
    }
   ]
  },
  {
   "title": "Clone schema owned data",
   "type": "timeseries",
   "description": "Amount of clone data owned by the selected schema.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance,database_name,schema_name) (last_over_time(snowflake_table_clone_bytes{job=\"integrations/snowflake\",job=~\"$job\",instance=~\"$instance\", database_name=~\"$database_name\", schema_name=~\"$schema_name\"}[24h]))",
     "legendFormat": "{{instance}} - {{database_name}} - {{schema_name}}"
    }
   ]
  },
  {
   "title": "Time travel schema owned data",
   "type": "timeseries",
   "description": "Amount of Time Travel data owned by the selected schema.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance,database_name,schema_name) (last_over_time(snowflake_table_time_travel_bytes{job=\"integrations/snowflake\",job=~\"$job\",instance=~\"$instance\", database_name=~\"$database_name\", schema_name=~\"$schema_name\"}[24h]))",
     "legendFormat": "{{instance}} - {{database_name}} - {{schema_name}}"
    }
   ]
  },
  {
   "title": "Top 5 largest tables",
   "type": "table",
   "description": "The top 5 largest tables that belong to the selected schema.",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "last_over_time(snowflake_table_active_bytes{job=\"integrations/snowflake\",job=~\"$job\",instance=~\"$instance\", database_name=~\"$database_name\", schema_name=~\"$schema_name\"}[24h])",
     "legendFormat": "{{instance}} - {{database_name}} - {{schema_name}}"
    }
   ]
  },
  {
   "title": "Deleted tables",
   "type": "stat",
   "description": "The number of tables that have been purged from storage.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "snowflake_table_deleted_tables{job=\"integrations/snowflake\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - {{database_name}} - {{schema_name}}"
    }
   ]
  },
  { "title": "Table data", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 25 } },
  {
   "title": "Active table owned data",
   "type": "timeseries",
   "description": "Amount of active data owned by the selected table.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance,database_name,schema_name, table_name) (last_over_time(snowflake_table_active_bytes{job=\"integrations/snowflake\",job=~\"$job\",instance=~\"$instance\", database_name=~\"$database_name\", schema_name=~\"$schema_name\", table_name=~\"$table_name\"}[24h]))",
     "legendFormat": "{{instance}} - {{database_name}} - {{schema_name}} - {{table_name}}"
    }
   ]
  },
  {
   "title": "Fail-safe table owned data",
   "type": "timeseries",
   "description": "Amount of fail-safe data owned by the selected table.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance,database_name,schema_name, table_name) (last_over_time(snowflake_table_failsafe_bytes{job=\"integrations/snowflake\",job=~\"$job\",instance=~\"$instance\", database_name=~\"$database_name\", schema_name=~\"$schema_name\", table_name=~\"$table_name\"}[24h]))",
     "legendFormat": "{{instance}} - {{database_name}} - {{schema_name}} - {{table_name}}"
    }
   ]
  },
  {
   "title": "Time travel table owned data",
   "type": "timeseries",
   "description": "Amount of Time Travel data owned by the selected table.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance,database_name,schema_name, table_name) (last_over_time(snowflake_table_time_travel_bytes{job=\"integrations/snowflake\",job=~\"$job\",instance=~\"$instance\", database_name=~\"$database_name\", schema_name=~\"$schema_name\", table_name=~\"$table_name\"}[24h]))",
     "legendFormat": "{{instance}} - {{database_name}} - {{schema_name}} - {{table_name}}"
    }
   ]
  },
  {
   "title": "Clone table owned data",
   "type": "timeseries",
   "description": "Amount of clone data owned by the selected table.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance,database_name,schema_name, table_name) (last_over_time(snowflake_table_clone_bytes{job=\"integrations/snowflake\",job=~\"$job\",instance=~\"$instance\", database_name=~\"$database_name\", schema_name=~\"$schema_name\", table_name=~\"$table_name\"}[24h]))",
     "legendFormat": "{{instance}} - {{database_name}} - {{schema_name}} - {{table_name}}"
    }
   ]
  }
 ]
}