{
 "title": "Snowflake overview",
 "tags": [ "snowflake-mixin" ],
 "time": { "from": "now-8h", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(snowflake_successful_login_rate{job=\"integrations/snowflake\"}, job)"
   },
   {
    "name": "instance",
    "label": "Exporter instance",
    "query": "label_values(snowflake_successful_login_rate{job=\"integrations/snowflake\",job=~\"$job\"}, instance)"
   },
   {
    "name": "warehouse",
    "label": "Warehouse",
    "query": "label_values(snowflake_table_active_bytes{job=\"integrations/snowflake\",job=~\"$job\",instance=~\"$instance\"}, warehouse)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Successful login attempts",
   "type": "gauge",
   "description": "Percentage of total login attempts that were successful.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job,instance) (snowflake_successful_login_rate{job=\"integrations/snowflake\",job=~\"$job\",instance=~\"$instance\"}) / sum by (job,instance) (snowflake_login_rate{job=\"integrations/snowflake\",job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "{{instance}} - Successful"
    }
   ]
  },
  {
   "title": "Failed login attempts",
   "type": "gauge",
   "description": "Percentage of total login attempts that failed.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job,instance) (snowflake_failed_login_rate{job=\"integrations/snowflake\",job=~\"$job\",instance=~\"$instance\"}) / sum by (job,instance) (snowflake_login_rate{job=\"integrations/snowflake\",job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "{{instance}} - Failed"
    }
   ]
  },
  {
   "title": "Login attempts",
   "type": "timeseries",
   "description": "Login attempt rate over the last 24 hours.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "logins/hr" } },
   "targets": [
    {
     "expr": "sum by (job,instance) (snowflake_login_rate{job=\"integrations/snowflake\",job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "{{instance}} - Total"
    },
    {
     "expr": "sum by (job,instance) (snowflake_failed_login_rate{job=\"integrations/snowflake\",job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "{{instance}} - Failed"
    },
    {
     "expr": "sum by (job,instance) (snowflake_successful_login_rate{job=\"integrations/snowflake\",job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "{{instance}} - Successful"
    }
   ]
  },
  {
   "title": "Warehouse activity",
   "type": "timeseries",
   "description": "Warehouse query activity for the warehouse selected by the Warehouse selector.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "snowflake_warehouse_executed_queries{job=\"integrations/snowflake\",job=~\"$job\",instance=~\"$instance\", name=~\"$warehouse\"}",
     "legendFormat": "{{instance}} - {{name}} - Executed query load"
    },
    {
     "expr": "snowflake_warehouse_overloaded_queue_size{job=\"integrations/snowflake\",job=~\"$job\",instance=~\"$instance\", name=~\"$warehouse\"}",
     "legendFormat": "{{instance}} - {{name}} - Overloaded queue load"
    },
    {
     "expr": "snowflake_warehouse_provisioning_queue_size{job=\"integrations/snowflake\",job=~\"$job\",instance=~\"$instance\", name=~\"$warehouse\"}",
     "legendFormat": "{{instance}} - {{name}} - Provisioning queue load"
    },
    {
     "expr": "snowflake_warehouse_blocked_queries{job=\"integrations/snowflake\",job=~\"$job\",instance=~\"$instance\", name=~\"$warehouse\"}",
     "legendFormat": "{{instance}} - {{name}} - Blocked query load"
    }
   ]
  },
  {
   "title": "Account storage usage",
   "type": "timeseries",
   "description": "Data storage used for the account.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "snowflake_storage_bytes{job=\"integrations/snowflake\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - Storage"
    },
    {
     "expr": "snowflake_stage_bytes{job=\"integrations/snowflake\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - Stage"
    },
    {
     "expr": "snowflake_failsafe_bytes{job=\"integrations/snowflake\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - Failsafe"
    }
   ]
  },
  { "title": "Billing", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 25 } },
  {
   "title": "Compute billing usage",
   "type": "timeseries",
   "description": "Compute billing usage for the account.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (job,instance) (last_over_time(snowflake_used_compute_credits{job=\"integrations/snowflake\",job=~\"$job\",instance=~\"$instance\"}[24h]) / 5)",
     "legendFormat": "{{instance}} - Compute usage"
    }
   ]
  },
  {
   "title": "Cloud services billing usage",
   "type": "timeseries",
   "description": "Cloud services billing usage for the account.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (job,instance) (last_over_time(snowflake_used_cloud_services_credits{job=\"integrations/snowflake\",job=~\"$job\",instance=~\"$instance\"}[24h]) / 1)",
     "legendFormat": "{{instance}} - Cloud services usage"
    }
   ]
  },
  {
   "title": "Average hourly credits used",
   "type": "timeseries",
   "description": "Number of billing credits used by the account.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (job,instance) (snowflake_used_compute_credits{job=\"integrations/snowflake\",job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "{{instance}} - Compute"
    },
    {
     "expr": "sum by (job,instance) (snowflake_used_cloud_services_credits{job=\"integrations/snowflake\",job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "{{instance}} - Service"
    }
   ]
  },
  {
   "title": "Autoclustering credits used",
   "type": "timeseries",
   "description": "Credits billed for automatic reclustering.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "snowflake_auto_clustering_credits{job=\"integrations/snowflake\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{database_name}} - {{schema_name}} - {{table_name}}"
    }
   ]
  },
  {
   "title": "Top 5 service compute credits used",
   "type": "table",
   "description": "The top 5 services that have the highest compute credit usages.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "snowflake_used_compute_credits{job=\"integrations/snowflake\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Top 5 service cloud service credits used",
   "type": "table",
   "description": "The top 5 services that have the highest compute credit usages.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "snowflake_used_cloud_services_credits{job=\"integrations/snowflake\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Top 5 warehouse compute credits used",
   "type": "table",
   "description": "The top 5 warehouses that have the highest compute credit usages.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "snowflake_warehouse_used_compute_credits{job=\"integrations/snowflake\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Top 5 warehouse cloud services credits used",
   "type": "table",
   "description": "The top 5 warehouses that have the highest services credit usages.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "snowflake_warehouse_used_cloud_service_credits{job=\"integrations/snowflake\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Top 5 database autoclustering credits used",
   "type": "table",
   "description": "The top 5 databases that have the highest autoclustering credit usages.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "sum by (job,instance, database_name) (snowflake_auto_clustering_credits{job=\"integrations/snowflake\",job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Top 5 table autoclustering credits used",
   "type": "table",
   "description": "The top 5 tables that have the highest autoclustering credit usages.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "snowflake_auto_clustering_credits{job=\"integrations/snowflake\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}