name: Build Exporter

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  detect-changes:
    name: Detect changes
    runs-on: ubuntu-latest
    outputs:
      exporter-changed: ${{ steps.changes.outputs.exporter_any_changed == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Detect changed files
        id: changes
        uses: step-security/changed-files@2e07db73e5ccdb319b9a6c7766bd46d39d304bad # v47.0.5
        with:
          files_yaml: |
            exporter:
              - '**/*.go'
              - 'go.mod'
              - 'go.sum'
              - 'Makefile'
              - 'Makefile.common'
              - '.promu.yml'
              - '.golangci.yml'

  setup:
    name: Setup
    needs: [detect-changes]
    if: needs.detect-changes.outputs.exporter-changed == 'true'
    uses: ./.github/workflows/setup.yml

  lint:
    name: Lint exporter
    needs: [detect-changes, setup]
    if: needs.detect-changes.outputs.exporter-changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Download Go modules
        run: go mod download

      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@0782b76014f15f24e22a438f30f308df42899ba1 # v1.3.0

      - name: golangci-lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
        with:
          version: v2.12.2
          args: --enable-only gosec
      
      - name: gosec-check
        run: make gosec-check

      - name: vuln-check
        run: make vuln-check

      - name: lint style
        run: make lint

  build:
    name: Build and test Go exporter
    needs: [setup, lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Download Go modules
        run: go mod download

      - name: Build
        run: make build

      - name: Test
        run: go test -v ./...
